// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message_generator.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenerateMessageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMessageRequest) Reset()         { *m = GenerateMessageRequest{} }
func (m *GenerateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateMessageRequest) ProtoMessage()    {}
func (*GenerateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_839dbe1f23eb05c5, []int{0}
}
func (m *GenerateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMessageRequest.Unmarshal(m, b)
}
func (m *GenerateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMessageRequest.Marshal(b, m, deterministic)
}
func (m *GenerateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMessageRequest.Merge(m, src)
}
func (m *GenerateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateMessageRequest.Size(m)
}
func (m *GenerateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMessageRequest proto.InternalMessageInfo

type GenerateMessageResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateMessageResponse) Reset()         { *m = GenerateMessageResponse{} }
func (m *GenerateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateMessageResponse) ProtoMessage()    {}
func (*GenerateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_839dbe1f23eb05c5, []int{1}
}
func (m *GenerateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateMessageResponse.Unmarshal(m, b)
}
func (m *GenerateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateMessageResponse.Marshal(b, m, deterministic)
}
func (m *GenerateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateMessageResponse.Merge(m, src)
}
func (m *GenerateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateMessageResponse.Size(m)
}
func (m *GenerateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateMessageResponse proto.InternalMessageInfo

func (m *GenerateMessageResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GenerateMessageRequest)(nil), "berrypost.v1.GenerateMessageRequest")
	proto.RegisterType((*GenerateMessageResponse)(nil), "berrypost.v1.GenerateMessageResponse")
}

func init() { proto.RegisterFile("message_generator.proto", fileDescriptor_839dbe1f23eb05c5) }

var fileDescriptor_839dbe1f23eb05c5 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x8d, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x4a, 0x2d, 0x2a, 0xaa, 0x2c, 0xc8, 0x2f, 0x2e, 0xd1, 0x2b,
	0x33, 0x54, 0x92, 0xe0, 0x12, 0x73, 0x87, 0x28, 0x48, 0xf5, 0x85, 0x68, 0x08, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x51, 0xd2, 0xe5, 0x12, 0xc7, 0x90, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3,
	0x8d, 0xaa, 0xb9, 0x24, 0x9d, 0x40, 0x06, 0x07, 0xe4, 0x17, 0x97, 0x40, 0xd5, 0xbb, 0xc3, 0x6c,
	0x16, 0x8a, 0xe3, 0xe2, 0x47, 0x33, 0x4b, 0x48, 0x45, 0x0f, 0xd9, 0x1d, 0x7a, 0xd8, 0x1d, 0x21,
	0xa5, 0x4a, 0x40, 0x15, 0xc4, 0x41, 0x4e, 0xac, 0x51, 0xcc, 0x89, 0x05, 0x99, 0x49, 0x6c, 0x60,
	0x1f, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0xb0, 0x96, 0x28, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BerryPostMessageGeneratorClient is the client API for BerryPostMessageGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BerryPostMessageGeneratorClient interface {
	GenerateMessage(ctx context.Context, in *GenerateMessageRequest, opts ...grpc.CallOption) (*GenerateMessageResponse, error)
}

type berryPostMessageGeneratorClient struct {
	cc *grpc.ClientConn
}

func NewBerryPostMessageGeneratorClient(cc *grpc.ClientConn) BerryPostMessageGeneratorClient {
	return &berryPostMessageGeneratorClient{cc}
}

func (c *berryPostMessageGeneratorClient) GenerateMessage(ctx context.Context, in *GenerateMessageRequest, opts ...grpc.CallOption) (*GenerateMessageResponse, error) {
	out := new(GenerateMessageResponse)
	err := c.cc.Invoke(ctx, "/berrypost.v1.BerryPostMessageGenerator/GenerateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BerryPostMessageGeneratorServer is the server API for BerryPostMessageGenerator service.
type BerryPostMessageGeneratorServer interface {
	GenerateMessage(context.Context, *GenerateMessageRequest) (*GenerateMessageResponse, error)
}

// UnimplementedBerryPostMessageGeneratorServer can be embedded to have forward compatible implementations.
type UnimplementedBerryPostMessageGeneratorServer struct {
}

func (*UnimplementedBerryPostMessageGeneratorServer) GenerateMessage(ctx context.Context, req *GenerateMessageRequest) (*GenerateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateMessage not implemented")
}

func RegisterBerryPostMessageGeneratorServer(s *grpc.Server, srv BerryPostMessageGeneratorServer) {
	s.RegisterService(&_BerryPostMessageGenerator_serviceDesc, srv)
}

func _BerryPostMessageGenerator_GenerateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BerryPostMessageGeneratorServer).GenerateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berrypost.v1.BerryPostMessageGenerator/GenerateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BerryPostMessageGeneratorServer).GenerateMessage(ctx, req.(*GenerateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BerryPostMessageGenerator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "berrypost.v1.BerryPostMessageGenerator",
	HandlerType: (*BerryPostMessageGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateMessage",
			Handler:    _BerryPostMessageGenerator_GenerateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_generator.proto",
}
